// Generated by CoffeeScript 1.4.0
(function() {
  var should;

  should = chai.should();

  mocha.setup('bdd');

  describe('Invoker', function() {
    describe('single invocation', function() {
      it('should get right response', function(done) {
        var invocation, utils;
        utils = new Invoker('Utils', ['add']);
        invocation = utils.add(1, 2)(function(result) {
          result.should.equal(3);
          return done();
        });
        return invocation.__calls.should.deep.equal([['Utils', 'add', [1, 2], void 0]]);
      });
      it('should send a bit more complicated arguments', function(done) {
        var invocation, utils;
        utils = new Invoker('Utils', ['addList']);
        invocation = utils.addList([1, 2, 3], [-1, 0, 1])(function(result) {
          result.should.deep.equal([0, 2, 4]);
          return done();
        });
        return invocation.__calls.should.deep.equal([['Utils', 'addList', [[1, 2, 3], [-1, 0, 1]], void 0]]);
      });
      return it('object as argument', function(done) {
        var dict, utils;
        utils = new Invoker('Utils', ['sortByValue']);
        dict = {
          a: 3,
          b: 2,
          c: 1
        };
        return utils.sortByValue(dict, 'desc')(function(result) {
          result.should.deep.equal([['a', 3], ['b', 2], ['c', 1]]);
          return done();
        });
      });
    });
    describe('multiple invocations', function() {
      return it('multiple invocations', function(done) {
        var dict, invocation, utils;
        utils = new Invoker('Utils', ['addList', 'sortByValue']);
        dict = {
          a: 1,
          b: 3,
          c: 2
        };
        invocation = Invoker.batch(function(invocation_done) {
          utils.sortByValue(dict, 'asc')(function(result) {
            return result.should.deep.equal([['a', 1], ['c', 2], ['b', 3]]);
          });
          utils.addList([1, 2], [2, 4])(function(result) {
            return result.should.deep.equal([3, 6]);
          });
          return invocation_done(function() {
            return done();
          });
        });
        return invocation.__calls.should.deep.equal([['Utils', 'sortByValue', [dict, 'asc'], void 0], ['Utils', 'addList', [[1, 2], [2, 4]], void 0]]);
      });
    });
    describe('multiple invokers', function() {
      var path, utils;
      path = new Invoker('Path', ['pwd']);
      utils = new Invoker('Utils', ['add']);
      it('should allow more than one instance', function(done) {
        return Invoker.batch(function(invocation_done) {
          path.pwd()(function(result) {
            return result.should.equal('/test');
          });
          utils.add(-1, 1)(function(result) {
            return result.should.equal(0);
          });
          return invocation_done(function() {
            return done();
          });
        });
      });
      it('should be able to make single request again', function(done) {
        return utils.add(99, 1)(function(sum) {
          sum.should.equal(100);
          return done();
        });
      });
      return it('should be able to make batch request again', function(done) {
        return Invoker.batch(function(invocation_done) {
          utils.add(1.5, -0.5)(function(sum) {
            return sum.should.equal(1);
          });
          return invocation_done(function() {
            return done();
          });
        });
      });
    });
    describe('access controll', function() {
      return it('should not allow access to certain methods', function(done) {
        var path;
        path = new Invoker('Path', ['scanDir']);
        return path.scanDir()({
          success: function(result) {
            throw {
              name: 'Error'
            };
            ({
              message: 'Error'
            });
            return done();
          },
          error: function(result, code) {
            code.should.equal(403);
            return done();
          }
        });
      });
    });
    describe('invoke', function() {
      return it('should send request immediately', function(done) {
        return Invoker.invoke(['Utils', 'add', [1, 2]], function(result) {
          result.should.equal(3);
          return done();
        });
      });
    });
    return describe('serverside object chache', function() {
      it('should remember previous object', function(done) {
        var user;
        user = new Invoker('User', ['create', 'getPosts', 'addPost'], ['foo']);
        return Invoker.batch(function(invocation_done) {
          user.create()(function() {});
          user.getPosts()(function(posts) {
            return posts.length.should.equal(0);
          });
          user.addPost({
            id: 1
          })(function() {});
          user.getPosts()(function(posts) {
            return posts.length.should.equal(1);
          });
          return invocation_done(function() {
            return done();
          });
        });
      });
      return it('should remember previous object again', function(done) {
        var user;
        user = new Invoker('User', ['create', 'getPosts', 'addPost'], ['foo']);
        return Invoker.batch(function(invocation_done) {
          user.create()(function() {});
          user.getPosts()(function(posts) {
            return posts.length.should.equal(0);
          });
          user.addPost({
            id: 1
          })(function() {});
          user.getPosts()(function(posts) {});
          user.addPost({
            id: 2
          })(function() {});
          user.getPosts()(function(posts) {
            return posts.length.should.equal(2);
          });
          return invocation_done(function() {
            return done();
          });
        });
      });
    });
  });

  describe('Signal', function() {
    describe('add', function() {
      var i, registration, signal, _i;
      signal = new Signal;
      for (i = _i = 1; _i <= 100; i = ++_i) {
        registration = signal.add(function(data) {});
        signal.remove(registration);
      }
      it('should use space efficiently', function() {
        return signal.__listeners.length.should.equal(1);
      });
      return it('should notify every listener', function() {
        var data_collection, _j;
        data_collection = [];
        for (i = _j = 1; _j <= 100; i = ++_j) {
          signal.add(function(data) {
            return data_collection.push(data);
          });
        }
        signal.dispatch(1);
        data_collection.should.deep.equal((function() {
          var _k, _results;
          _results = [];
          for (i = _k = 1; _k <= 100; i = ++_k) {
            _results.push(1);
          }
          return _results;
        })());
        data_collection.length = 0;
        signal.dispatch(' ');
        return data_collection.should.deep.equal((function() {
          var _k, _results;
          _results = [];
          for (i = _k = 1; _k <= 100; i = ++_k) {
            _results.push(' ');
          }
          return _results;
        })());
      });
    });
    return describe('once', function() {
      var data_collection, i, signal, _i;
      signal = new Signal;
      data_collection = [];
      for (i = _i = 1; _i <= 100; i = ++_i) {
        signal.once(function(data) {
          return data_collection.push(data);
        });
        signal.dispatch(i);
      }
      it('should use space efficiently', function() {
        return signal.__listeners.should.deep.equal([void 0]);
      });
      return it('should listen only once', function() {
        var _j, _results;
        return data_collection.should.deep.equal((function() {
          _results = [];
          for (_j = 1; _j <= 100; _j++){ _results.push(_j); }
          return _results;
        }).apply(this));
      });
    });
  });

  describe('Invocation', function() {
    return describe('abort', function() {
      return it('should abort', function() {
        var invocation, utils;
        utils = new Invoker('Utils', ['add']);
        invocation = utils.add(1, 2)(function(result) {
          result.should.equal(3);
          return console.log('no way to test it programmatically?');
        });
        return invocation.abort();
      });
    });
  });

  describe('getClass', function() {
    return describe('static method', function() {
      it('should be able to call static method without creating a new instance', function(done) {
        var Utils;
        Utils = getClass('Utils', ['add', 'addList']);
        return Utils.add(1, 2)(function(result) {
          result.should.equal(3);
          return done();
        });
      });
      return it('should be able to crate instance of class', function(done) {
        var User;
        User = getClass('User', ['save', 'listUsers']);
        return batchInvocations(function(invocation_done) {
          var user;
          User.listUsers()(function(users) {
            return users.length.should.equal(2);
          });
          user = new User('foo');
          user.save()(function(result) {
            return result.should.equal(true);
          });
          User.listUsers()(function(users) {
            return users.length.shoud.equal(3);
          });
          return invocation_done(function() {
            return done();
          });
        });
      });
    });
  });

}).call(this);
